# Generated by Django 4.2.8 on 2025-01-07 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_article_like_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='article_image',
            field=models.ImageField(blank=True, null=True, upload_to='article_images/', verbose_name='게시글 이미지'),
        ),
    ]
